package helio.builder.rmlmapper;

import helio.blueprints.TranslationUnit;
import helio.blueprints.UnitBuilder;
import helio.blueprints.exceptions.ExtensionNotFoundException;
import helio.blueprints.exceptions.IncompatibleMappingException;
import helio.blueprints.exceptions.IncorrectMappingException;
import helio.blueprints.exceptions.TranslationUnitExecutionException;

public class Main {

	
	public static String mapping = "@prefix rr: <http://www.w3.org/ns/r2rml#>.\n"
			+ "@prefix rml: <http://semweb.mmlab.be/ns/rml#>.\n"
			+ "@prefix ql: <http://semweb.mmlab.be/ns/ql#>.\n"
			+ "@prefix transit: <http://vocab.org/transit/terms/>.\n"
			+ "@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.\n"
			+ "@prefix grel: <http://users.ugent.be/~bjdmeest/function/grel.ttl#> .\n"
			+ "@prefix fnml: <http://semweb.mmlab.be/ns/fnml#> .\n"
			+ "@prefix fno: <https://w3id.org/function/ontology#> .\n"
			+ "@prefix foaf: <http://xmlns.com/foaf/0.1/> .\n"
			+ "@prefix wgs84_pos: <http://www.w3.org/2003/01/geo/wgs84_pos#>.\n"
			+ "@prefix vocab: <http://e-scooter.com/ontology#> .\n"
			+ "@base <http://e-scooter.com/resources/>.\n"
			+ "\n"
			+ "<#Trip> a rr:TriplesMap;\n"
			+ "  rml:logicalSource [\n"
			+ "    rml:source \"./E-Scooter_Trips_2019_sample_10_percent-updated.csv\" ;\n"
			+ "    rml:referenceFormulation ql:CSV \n"
			+ "  ];\n"
			+ "\n"
			+ "  rr:subjectMap [\n"
			+ "    rr:template \"http://e-scooter.com/resources/trip/{TripID}\";\n"
			+ "    rr:class vocab:Trip\n"
			+ "  ];\n"
			+ "  \n"
			+ "  rr:predicateObjectMap [\n"
			+ "    rr:predicate vocab:hasStartTime;\n"
			+ "    rr:objectMap [\n"
			+ "      rml:reference \"StartTime\";\n"
			+ "      rr:datatype xsd:dateTime\n"
			+ "    ]\n"
			+ "  ];\n"
			+ "\n"
			+ "  rr:predicateObjectMap [\n"
			+ "    rr:predicate vocab:hasEndTime;\n"
			+ "    rr:objectMap [\n"
			+ "      rml:reference \"EndTime\";\n"
			+ "      rr:datatype xsd:dateTime\n"
			+ "    ]\n"
			+ "  ];\n"
			+ "\n"
			+ "  rr:predicateObjectMap [\n"
			+ "    rr:predicate vocab:hasTripDistance;\n"
			+ "    rr:objectMap [\n"
			+ "      rml:reference \"TripDistance\";\n"
			+ "      rr:datatype xsd:double\n"
			+ "    ]\n"
			+ "  ];\n"
			+ "\n"
			+ "  rr:predicateObjectMap [\n"
			+ "    rr:predicate vocab:hasTripDuration;\n"
			+ "    rr:objectMap [\n"
			+ "      rml:reference \"TripDuration\";\n"
			+ "      rr:datatype xsd:double\n"
			+ "    ]\n"
			+ "  ];\n"
			+ "\n"
			+ "  rr:predicateObjectMap [\n"
			+ "    rr:predicate vocab:hasAccuracy;\n"
			+ "    rr:objectMap [\n"
			+ "      rml:reference \"Accuracy\";\n"
			+ "      rr:datatype xsd:double\n"
			+ "    ]\n"
			+ "  ];\n"
			+ "\n"
			+ "  rr:predicateObjectMap [\n"
			+ "    rr:predicate vocab:hasStartCensusTract;\n"
			+ "    rr:objectMap [\n"
			+ "      rml:reference \"StartCensusTract\";\n"
			+ "      rr:datatype xsd:double\n"
			+ "    ]\n"
			+ "  ];\n"
			+ "\n"
			+ "  rr:predicateObjectMap [\n"
			+ "    rr:predicate vocab:hasEndCensusTract;\n"
			+ "    rr:objectMap [\n"
			+ "      rml:reference \"EndCensusTract\";\n"
			+ "      rr:datatype xsd:double\n"
			+ "    ]\n"
			+ "  ];\n"
			+ "\n"
			+ "  rr:predicateObjectMap [\n"
			+ "    rr:predicate vocab:hasStartCommunity;\n"
			+ "    rr:objectMap [\n"
			+ "      rr:parentTriplesMap <#StartCommunity>;\n"
			+ "      rr:joinCondition [\n"
			+ "        rr:child \"TripID\";\n"
			+ "        rr:parent \"TripID\"\n"
			+ "      ]\n"
			+ "    ]\n"
			+ "  ];\n"
			+ "\n"
			+ "  rr:predicateObjectMap [\n"
			+ "    rr:predicate vocab:hasEndCommunity;\n"
			+ "    rr:objectMap [\n"
			+ "      rr:parentTriplesMap <#EndCommunity>;\n"
			+ "      rr:joinCondition [\n"
			+ "        rr:child \"TripID\";\n"
			+ "        rr:parent \"TripID\"\n"
			+ "      ]\n"
			+ "    ]\n"
			+ "  ];\n"
			+ "\n"
			+ "  rr:predicateObjectMap [\n"
			+ "    rr:predicate vocab:hasStartCentroid;\n"
			+ "    rr:objectMap [\n"
			+ "      rr:parentTriplesMap <#StartCentroid>;\n"
			+ "      rr:joinCondition [\n"
			+ "        rr:child \"TripID\";\n"
			+ "        rr:parent \"TripID\"\n"
			+ "      ]\n"
			+ "    ]\n"
			+ "  ];\n"
			+ "\n"
			+ "  rr:predicateObjectMap [\n"
			+ "    rr:predicate vocab:hasEndCentroid;\n"
			+ "    rr:objectMap [\n"
			+ "      rr:parentTriplesMap <#EndCentroid>;\n"
			+ "      rr:joinCondition [\n"
			+ "        rr:child \"TripID\";\n"
			+ "        rr:parent \"TripID\"\n"
			+ "      ]\n"
			+ "    ]\n"
			+ "  ] .\n"
			+ "\n"
			+ "<#StartCommunity> a rr:TriplesMap;\n"
			+ "\n"
			+ "  rml:logicalSource [\n"
			+ "      rml:source \"./E-Scooter_Trips_2019_sample_10_percent-updated.csv\" ;\n"
			+ "      rml:referenceFormulation ql:CSV \n"
			+ "    ];\n"
			+ "\n"
			+ "  rr:subjectMap [\n"
			+ "    rr:template \"http://e-scooter.com/resources/community/{StartCommunityAreaNumber}\";\n"
			+ "    rr:class vocab:Community\n"
			+ "  ];\n"
			+ "\n"
			+ "  rr:predicateObjectMap [\n"
			+ "    rr:predicate vocab:hasAreaNumber;\n"
			+ "    rr:objectMap [\n"
			+ "      rml:reference \"StartCommunityAreaNumber\";\n"
			+ "      rr:datatype xsd:double\n"
			+ "    ]\n"
			+ "  ];\n"
			+ "\n"
			+ "  rr:predicateObjectMap [\n"
			+ "    rr:predicate vocab:hasAreaName;\n"
			+ "    rr:objectMap [\n"
			+ "      rml:reference \"StartCommunityAreaName\";\n"
			+ "      rr:datatype xsd:string\n"
			+ "    ]\n"
			+ "  ];\n"
			+ "\n"
			+ "  rr:predicateObjectMap [\n"
			+ "    rr:predicate vocab:sameAsWikidata;\n"
			+ "    rr:objectMap [\n"
			+ "      rml:reference \"start_com_wikidata\";\n"
			+ "      rr:termType rr:IRI\n"
			+ "    ]\n"
			+ "  ].\n"
			+ "\n"
			+ "<#EndCommunity> a rr:TriplesMap;\n"
			+ "\n"
			+ "  rml:logicalSource [\n"
			+ "      rml:source \"./E-Scooter_Trips_2019_sample_10_percent-updated.csv\" ;\n"
			+ "      rml:referenceFormulation ql:CSV \n"
			+ "    ];\n"
			+ "\n"
			+ "  rr:subjectMap [\n"
			+ "    rr:template \"http://e-scooter.com/resources/community/{EndCommunityAreaNumber}\";\n"
			+ "    rr:class vocab:Community\n"
			+ "  ];\n"
			+ "\n"
			+ "  rr:predicateObjectMap [\n"
			+ "    rr:predicate vocab:hasAreaNumber;\n"
			+ "    rr:objectMap [\n"
			+ "      rml:reference \"EndCommunityAreaNumber\";\n"
			+ "      rr:datatype xsd:double\n"
			+ "    ]\n"
			+ "  ];\n"
			+ "\n"
			+ "  rr:predicateObjectMap [\n"
			+ "    rr:predicate vocab:hasAreaName;\n"
			+ "    rr:objectMap [\n"
			+ "      rml:reference \"EndCommunityAreaName\";\n"
			+ "      rr:datatype xsd:string\n"
			+ "    ]\n"
			+ "  ];\n"
			+ "\n"
			+ "  rr:predicateObjectMap [\n"
			+ "    rr:predicate vocab:sameAsWikidata;\n"
			+ "    rr:objectMap [\n"
			+ "      rml:reference \"end_com_wikidata\";\n"
			+ "      rr:termType rr:IRI\n"
			+ "    ]\n"
			+ "  ].\n"
			+ "\n"
			+ "<#StartCentroid> a rr:TriplesMap;\n"
			+ "\n"
			+ "  rml:logicalSource [\n"
			+ "      rml:source \"./E-Scooter_Trips_2019_sample_10_percent-updated.csv\" ;\n"
			+ "      rml:referenceFormulation ql:CSV \n"
			+ "    ];\n"
			+ "\n"
			+ "  rr:subjectMap [\n"
			+ "    rr:template \"http://e-scooter.com/resources/centroid/CENT_{StartCentroidLatitude}_{StartCentroidLongitude}\";\n"
			+ "    rr:class vocab:Centroid\n"
			+ "  ];\n"
			+ "\n"
			+ "  rr:predicateObjectMap [\n"
			+ "    rr:predicate vocab:hasLocation;\n"
			+ "    rr:objectMap [\n"
			+ "      rr:parentTriplesMap <#StartLocation>;\n"
			+ "      rr:joinCondition [\n"
			+ "        rr:child \"TripID\";\n"
			+ "        rr:parent \"TripID\"\n"
			+ "      ]\n"
			+ "    ]\n"
			+ "  ] .\n"
			+ "\n"
			+ "<#EndCentroid> a rr:TriplesMap;\n"
			+ "\n"
			+ "  rml:logicalSource [\n"
			+ "      rml:source \"./E-Scooter_Trips_2019_sample_10_percent-updated.csv\" ;\n"
			+ "      rml:referenceFormulation ql:CSV \n"
			+ "    ];\n"
			+ "\n"
			+ "  rr:subjectMap [\n"
			+ "    rr:template \"http://e-scooter.com/resources/centroid/CENT_{EndCentroidLatitude}_{EndCentroidLongitude}\";\n"
			+ "    rr:class vocab:Centroid\n"
			+ "  ];\n"
			+ "\n"
			+ "  rr:predicateObjectMap [\n"
			+ "    rr:predicate vocab:hasLocation;\n"
			+ "    rr:objectMap [\n"
			+ "      rr:parentTriplesMap <#EndLocation>;\n"
			+ "      rr:joinCondition [\n"
			+ "        rr:child \"TripID\";\n"
			+ "        rr:parent \"TripID\"\n"
			+ "      ]\n"
			+ "    ]\n"
			+ "  ] .\n"
			+ "\n"
			+ "<#StartLocation> a rr:TriplesMap;\n"
			+ "\n"
			+ "  rml:logicalSource [\n"
			+ "      rml:source \"./E-Scooter_Trips_2019_sample_10_percent-updated.csv\" ;\n"
			+ "      rml:referenceFormulation ql:CSV \n"
			+ "    ];\n"
			+ "\n"
			+ "  rr:subjectMap [\n"
			+ "    rr:template \"http://e-scooter.com/resources/location/{StartCentroidLatitude}_{StartCentroidLongitude}\";\n"
			+ "    rr:class vocab:Location\n"
			+ "  ];\n"
			+ "\n"
			+ "  rr:predicateObjectMap [\n"
			+ "    rr:predicate vocab:hasLatitude;\n"
			+ "    rr:objectMap [\n"
			+ "      rml:reference \"StartCentroidLatitude\";\n"
			+ "      rr:datatype xsd:double\n"
			+ "    ]\n"
			+ "  ];\n"
			+ "\n"
			+ "  rr:predicateObjectMap [\n"
			+ "    rr:predicate vocab:hasLongitude;\n"
			+ "    rr:objectMap [\n"
			+ "      rml:reference \"StartCentroidLongitude\";\n"
			+ "      rr:datatype xsd:double\n"
			+ "    ]\n"
			+ "  ] .\n"
			+ "\n"
			+ "<#EndLocation> a rr:TriplesMap;\n"
			+ "\n"
			+ "  rml:logicalSource [\n"
			+ "      rml:source \"./E-Scooter_Trips_2019_sample_10_percent-updated.csv\" ;\n"
			+ "      rml:referenceFormulation ql:CSV \n"
			+ "    ];\n"
			+ "\n"
			+ "  rr:subjectMap [\n"
			+ "    rr:template \"http://e-scooter.com/resources/location/{EndCentroidLatitude}_{EndCentroidLongitude}\";\n"
			+ "    rr:class vocab:Location\n"
			+ "  ];\n"
			+ "\n"
			+ "  rr:predicateObjectMap [\n"
			+ "    rr:predicate vocab:hasLatitude;\n"
			+ "    rr:objectMap [\n"
			+ "      rml:reference \"EndCentroidLatitude\";\n"
			+ "      rr:datatype xsd:double\n"
			+ "    ]\n"
			+ "  ];\n"
			+ "\n"
			+ "  rr:predicateObjectMap [\n"
			+ "    rr:predicate vocab:hasLongitude;\n"
			+ "    rr:objectMap [\n"
			+ "      rml:reference \"EndCentroidLongitude\";\n"
			+ "      rr:datatype xsd:double\n"
			+ "    ]\n"
			+ "  ] .";
	
	
	public static void main(String[] args) throws IncompatibleMappingException, TranslationUnitExecutionException, IncorrectMappingException, ExtensionNotFoundException {
		UnitBuilder wrap = new RmlUnitBuilder();
		TranslationUnit unit = wrap.parseMapping(mapping).iterator().next();
		unit.getTask().run();
		System.out.println(unit.getDataTranslated());
		

	}

}
